// FA_Gate.v
// Carried forward unchanged from Task 2, as the task requires.
//
// Gate-level model of a 1-bit full adder, now with explicit gate delays.
// From this task onward, every gate/assign you write in this lab should
// have an explicit delay -- it's the default way we'll be writing Verilog
// from here on, not a special add-on.
//
// Part (a): add a CONSTANT delay to every gate below, e.g.:
//   xor #(2) (ps, a, b);
// Do this for all five gates, then complete ripple_adder.v (this folder)
// using this full adder, and simulate against tb.v.
//
// Part (b): after completing (a), change every gate's delay from a single
// constant value to a RISE/FALL pair instead, e.g.:
//   xor #(2,3) (ps, a, b);   // rise delay = 2, fall delay = 3
// This tells the simulator to use a different delay depending on whether
// the gate's output is transitioning 0->1 (rise) or 1->0 (fall) -- real
// gates are rarely symmetric this way. Re-simulate with the SAME
// ripple_adder.v and tb.v; nothing else needs to change.
//
// Part (a) is the version kept below: one constant delay of 2 on every
// gate, so that the timing numbers stay directly comparable with the
// adders built out of this cell in Tasks 3-5. For part (b) swap each
// #(2) for a #(2,3) pair -- the carry chain then settles at slightly
// different times depending on which way each carry bit is moving.

module FA_Gate(
  input  a,
  input  b,
  input  cin,
  output sum,
  output cout
);
  // ps   : half-adder sum of a and b       (the "propagate" term)
  // pc1  : carry generated by a and b alone
  // pc2  : carry propagated from cin
  wire ps, pc1, pc2;

  xor #(2) (ps,   a,   b);
  xor #(2) (sum,  ps,  cin);
  and #(2) (pc1,  a,   b);
  and #(2) (pc2,  ps,  cin);
  or  #(2) (cout, pc1, pc2);

endmodule
